<?php

define('API_ERROR_CODE_SUCCESS', 10000);
define('API_ERROR_CODE_FAIL', 10001);
define('API_ERROR_CODE_LACK_PARAMS', 10002);
define('API_ERROR_CODE_INVALID_SIGN_TYPE', 10003);
define('API_ERROR_CODE_INVALID_APP_ID', 10004);
define('API_ERROR_CODE_INVALID_VERSION', 10005);
define('API_ERROR_CODE_INVALID_METHOD', 10006);
define('API_ERROR_CODE_INVALID_SIGN', 10007);
define('API_ERROR_CODE_LACK_TOKEN', 10008);
define('API_ERROR_CODE_INVALID_TOKEN', 10009);
define('API_ERROR_CODE_INVALID_PARAMS', 10010);
define('API_ERROR_CODE_SYSTEM_ERROR', 10011);
define('API_ERROR_CODE_NOT_AUTH', 10012);
define('API_ERROR_CODE_NO_DATA', 10013);
$GLOBALS['__API_ERROR_CODE'] = [
    API_ERROR_CODE_SUCCESS => 'SUCCESS',
    API_ERROR_CODE_FAIL => 'FAIL',
    API_ERROR_CODE_LACK_PARAMS => '缺少必要参数',
    API_ERROR_CODE_INVALID_SIGN_TYPE => '无效签名类型',
    API_ERROR_CODE_INVALID_APP_ID => '无效app_id',
    API_ERROR_CODE_INVALID_VERSION => '无效的版本号',
    API_ERROR_CODE_INVALID_METHOD => '无效的方法名',
    API_ERROR_CODE_INVALID_SIGN => '无效签名',
    API_ERROR_CODE_LACK_TOKEN => '登录令牌必传',
    API_ERROR_CODE_INVALID_TOKEN => '登录已失效，请重新登录',
    API_ERROR_CODE_INVALID_PARAMS => '无效参数',
    API_ERROR_CODE_SYSTEM_ERROR => '系统错误',
    API_ERROR_CODE_NOT_AUTH => '无权限访问',
    API_ERROR_CODE_NO_DATA => '未查询到数据',
];

define('YES', 1);
define('NO', 0);