<?php

define('API_ERROR_CODE_SUCCESS', 10000);//成功
define('API_ERROR_CODE_FAIL', 10001);//失败
define('API_ERROR_CODE_LACK_PARAMS', 10002);//缺少必要参数
define('API_ERROR_CODE_INVALID_SIGN_TYPE', 10003);//无效的签名类型
define('API_ERROR_CODE_INVALID_APP_ID', 10004);//无效的app_id
define('API_ERROR_CODE_INVALID_VERSION', 10005);//无效的版本号
define('API_ERROR_CODE_INVALID_METHOD', 10006);//无效的方法名
define('API_ERROR_CODE_INVALID_SIGN', 10007);//无效的签名
define('API_ERROR_CODE_LACK_TOKEN', 10008);//token必传
define('API_ERROR_CODE_INVALID_TOKEN', 10009);//无效的token
define('API_ERROR_CODE_INVALID_PARAMS', 10010);//无效的参数
define('API_ERROR_CODE_SYSTEM_ERROR', 10011);//系统错误
define('API_ERROR_CODE_NOT_AUTH', 10012);//无权限调用
define('API_ERROR_CODE_NO_DATA', 10013);//未查询到数据
$GLOBALS['__API_ERROR_CODE'] = [
    API_ERROR_CODE_SUCCESS => 'SUCCESS',
    API_ERROR_CODE_FAIL => 'FAIL',
    API_ERROR_CODE_LACK_PARAMS => '缺少必要参数',
    API_ERROR_CODE_INVALID_SIGN_TYPE => '无效的签名类型',
    API_ERROR_CODE_INVALID_APP_ID => '无效的app_id',
    API_ERROR_CODE_INVALID_VERSION => '无效的版本号',
    API_ERROR_CODE_INVALID_METHOD => '无效的方法名',
    API_ERROR_CODE_INVALID_SIGN => '无效的签名',
    API_ERROR_CODE_LACK_TOKEN => 'token必传',
    API_ERROR_CODE_INVALID_TOKEN => '登录已失效，请重新登录',
    API_ERROR_CODE_INVALID_PARAMS => '无效的参数',
    API_ERROR_CODE_SYSTEM_ERROR => '系统错误',
    API_ERROR_CODE_NOT_AUTH => '无权限调用',
    API_ERROR_CODE_NO_DATA => '未查询到数据',
];